# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NewGDToolMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setWindowOpacity(1.0)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gd_type_tab = QtWidgets.QTabWidget(self.centralwidget)
        self.gd_type_tab.setGeometry(QtCore.QRect(10, 10, 1261, 651))
        self.gd_type_tab.setObjectName("gd_type_tab")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 1251, 621))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gd_main_hbox = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.gd_main_hbox.setContentsMargins(0, 0, 0, 0)
        self.gd_main_hbox.setObjectName("gd_main_hbox")
        self.gd_data_edit_vbox = QtWidgets.QVBoxLayout()
        self.gd_data_edit_vbox.setObjectName("gd_data_edit_vbox")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gd_data_edit_vbox.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gd_name_lbl = QtWidgets.QLabel(self.layoutWidget)
        self.gd_name_lbl.setObjectName("gd_name_lbl")
        self.horizontalLayout.addWidget(self.gd_name_lbl)
        self.gd_name_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.gd_name_edit.setObjectName("gd_name_edit")
        self.horizontalLayout.addWidget(self.gd_name_edit)
        self.gd_data_edit_vbox.addLayout(self.horizontalLayout)
        self.gd_name_hline = QtWidgets.QFrame(self.layoutWidget)
        self.gd_name_hline.setFrameShape(QtWidgets.QFrame.HLine)
        self.gd_name_hline.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.gd_name_hline.setObjectName("gd_name_hline")
        self.gd_data_edit_vbox.addWidget(self.gd_name_hline)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gd_tri_lbl = QtWidgets.QLabel(self.layoutWidget)
        self.gd_tri_lbl.setObjectName("gd_tri_lbl")
        self.horizontalLayout_2.addWidget(self.gd_tri_lbl)
        self.gd_tri_type_cbox = QtWidgets.QComboBox(self.layoutWidget)
        self.gd_tri_type_cbox.setObjectName("gd_tri_type_cbox")
        self.horizontalLayout_2.addWidget(self.gd_tri_type_cbox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gd_tri_cont1_lbl = QtWidgets.QLabel(self.layoutWidget)
        self.gd_tri_cont1_lbl.setObjectName("gd_tri_cont1_lbl")
        self.horizontalLayout_3.addWidget(self.gd_tri_cont1_lbl)
        self.gd_tri_cont1_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.gd_tri_cont1_edit.setObjectName("gd_tri_cont1_edit")
        self.horizontalLayout_3.addWidget(self.gd_tri_cont1_edit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gd_tri_cont2_lbl = QtWidgets.QLabel(self.layoutWidget)
        self.gd_tri_cont2_lbl.setObjectName("gd_tri_cont2_lbl")
        self.horizontalLayout_4.addWidget(self.gd_tri_cont2_lbl)
        self.gd_tri_cont2_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.gd_tri_cont2_edit.setObjectName("gd_tri_cont2_edit")
        self.horizontalLayout_4.addWidget(self.gd_tri_cont2_edit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gd_tri_cont3_lbl = QtWidgets.QLabel(self.layoutWidget)
        self.gd_tri_cont3_lbl.setObjectName("gd_tri_cont3_lbl")
        self.horizontalLayout_5.addWidget(self.gd_tri_cont3_lbl)
        self.gd_tri_cont3_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.gd_tri_cont3_edit.setObjectName("gd_tri_cont3_edit")
        self.horizontalLayout_5.addWidget(self.gd_tri_cont3_edit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_19.addLayout(self.verticalLayout_2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gd_tri_data_tree = QtWidgets.QTreeWidget(self.layoutWidget)
        self.gd_tri_data_tree.setObjectName("gd_tri_data_tree")
        self.gd_tri_data_tree.headerItem().setText(0, "TriggerDataIndex")
        self.verticalLayout_5.addWidget(self.gd_tri_data_tree)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.gd_tri_input_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.gd_tri_input_btn.setObjectName("gd_tri_input_btn")
        self.horizontalLayout_18.addWidget(self.gd_tri_input_btn)
        self.gd_tri_remove_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.gd_tri_remove_btn.setObjectName("gd_tri_remove_btn")
        self.horizontalLayout_18.addWidget(self.gd_tri_remove_btn)
        self.verticalLayout_5.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19.addLayout(self.verticalLayout_5)
        self.horizontalLayout_25.addLayout(self.horizontalLayout_19)
        self.gd_tri_and_cond_vline = QtWidgets.QFrame(self.layoutWidget)
        self.gd_tri_and_cond_vline.setFrameShape(QtWidgets.QFrame.VLine)
        self.gd_tri_and_cond_vline.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.gd_tri_and_cond_vline.setObjectName("gd_tri_and_cond_vline")
        self.horizontalLayout_25.addWidget(self.gd_tri_and_cond_vline)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gd_cond_isenable_check = QtWidgets.QCheckBox(self.layoutWidget)
        self.gd_cond_isenable_check.setObjectName("gd_cond_isenable_check")
        self.verticalLayout_3.addWidget(self.gd_cond_isenable_check)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.gd_cond_type_lbl = QtWidgets.QLabel(self.layoutWidget)
        self.gd_cond_type_lbl.setObjectName("gd_cond_type_lbl")
        self.horizontalLayout_6.addWidget(self.gd_cond_type_lbl)
        self.gd_cond_type_box = QtWidgets.QComboBox(self.layoutWidget)
        self.gd_cond_type_box.setObjectName("gd_cond_type_box")
        self.horizontalLayout_6.addWidget(self.gd_cond_type_box)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.gd_cond_cont1_lbl = QtWidgets.QLabel(self.layoutWidget)
        self.gd_cond_cont1_lbl.setObjectName("gd_cond_cont1_lbl")
        self.horizontalLayout_7.addWidget(self.gd_cond_cont1_lbl)
        self.gd_cond_cont1_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.gd_cond_cont1_edit.setObjectName("gd_cond_cont1_edit")
        self.horizontalLayout_7.addWidget(self.gd_cond_cont1_edit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.gd_cond_cont2_lbl = QtWidgets.QLabel(self.layoutWidget)
        self.gd_cond_cont2_lbl.setObjectName("gd_cond_cont2_lbl")
        self.horizontalLayout_8.addWidget(self.gd_cond_cont2_lbl)
        self.gd_cond_cont2_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.gd_cond_cont2_edit.setObjectName("gd_cond_cont2_edit")
        self.horizontalLayout_8.addWidget(self.gd_cond_cont2_edit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.gd_cond_cont3_lbl = QtWidgets.QLabel(self.layoutWidget)
        self.gd_cond_cont3_lbl.setObjectName("gd_cond_cont3_lbl")
        self.horizontalLayout_9.addWidget(self.gd_cond_cont3_lbl)
        self.gd_cond_cont3_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.gd_cond_cont3_edit.setObjectName("gd_cond_cont3_edit")
        self.horizontalLayout_9.addWidget(self.gd_cond_cont3_edit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_21.addLayout(self.verticalLayout_3)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gd_cond_data_tree = QtWidgets.QTreeWidget(self.layoutWidget)
        self.gd_cond_data_tree.setObjectName("gd_cond_data_tree")
        self.gd_cond_data_tree.headerItem().setText(0, "ConditionDataIndex")
        self.verticalLayout_6.addWidget(self.gd_cond_data_tree)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.gd_cond_input_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.gd_cond_input_btn.setObjectName("gd_cond_input_btn")
        self.horizontalLayout_20.addWidget(self.gd_cond_input_btn)
        self.gd_cond_remove_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.gd_cond_remove_btn.setObjectName("gd_cond_remove_btn")
        self.horizontalLayout_20.addWidget(self.gd_cond_remove_btn)
        self.verticalLayout_6.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21.addLayout(self.verticalLayout_6)
        self.horizontalLayout_25.addLayout(self.horizontalLayout_21)
        self.gd_data_edit_vbox.addLayout(self.horizontalLayout_25)
        self.gd_tri_and_cond_hline = QtWidgets.QFrame(self.layoutWidget)
        self.gd_tri_and_cond_hline.setFrameShape(QtWidgets.QFrame.HLine)
        self.gd_tri_and_cond_hline.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.gd_tri_and_cond_hline.setObjectName("gd_tri_and_cond_hline")
        self.gd_data_edit_vbox.addWidget(self.gd_tri_and_cond_hline)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.gd_nd_isclick_lbl = QtWidgets.QLabel(self.layoutWidget)
        self.gd_nd_isclick_lbl.setObjectName("gd_nd_isclick_lbl")
        self.horizontalLayout_10.addWidget(self.gd_nd_isclick_lbl)
        self.gd_nd_isclick_box = QtWidgets.QComboBox(self.layoutWidget)
        self.gd_nd_isclick_box.setObjectName("gd_nd_isclick_box")
        self.gd_nd_isclick_box.addItem("")
        self.gd_nd_isclick_box.addItem("")
        self.horizontalLayout_10.addWidget(self.gd_nd_isclick_box)
        self.horizontalLayout_10.setStretch(1, 10)
        self.verticalLayout_9.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.gd_nd_isauto_lbl = QtWidgets.QLabel(self.layoutWidget)
        self.gd_nd_isauto_lbl.setObjectName("gd_nd_isauto_lbl")
        self.horizontalLayout_11.addWidget(self.gd_nd_isauto_lbl)
        self.gd_nd_isauto_box = QtWidgets.QComboBox(self.layoutWidget)
        self.gd_nd_isauto_box.setObjectName("gd_nd_isauto_box")
        self.horizontalLayout_11.addWidget(self.gd_nd_isauto_box)
        self.horizontalLayout_11.setStretch(1, 10)
        self.verticalLayout_9.addLayout(self.horizontalLayout_11)
        self.gd_dodata_isclick_and_isauto_hline = QtWidgets.QFrame(self.layoutWidget)
        self.gd_dodata_isclick_and_isauto_hline.setFrameShape(QtWidgets.QFrame.HLine)
        self.gd_dodata_isclick_and_isauto_hline.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.gd_dodata_isclick_and_isauto_hline.setObjectName("gd_dodata_isclick_and_isauto_hline")
        self.verticalLayout_9.addWidget(self.gd_dodata_isclick_and_isauto_hline)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.gd_nd_dotype_lbl = QtWidgets.QLabel(self.layoutWidget)
        self.gd_nd_dotype_lbl.setObjectName("gd_nd_dotype_lbl")
        self.horizontalLayout_12.addWidget(self.gd_nd_dotype_lbl)
        self.gd_nd_dotype_box = QtWidgets.QComboBox(self.layoutWidget)
        self.gd_nd_dotype_box.setObjectName("gd_nd_dotype_box")
        self.horizontalLayout_12.addWidget(self.gd_nd_dotype_box)
        self.horizontalLayout_12.setStretch(1, 10)
        self.verticalLayout_8.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.gd_nd_cont1_lbl = QtWidgets.QLabel(self.layoutWidget)
        self.gd_nd_cont1_lbl.setObjectName("gd_nd_cont1_lbl")
        self.horizontalLayout_13.addWidget(self.gd_nd_cont1_lbl)
        self.gd_nd_cont1_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.gd_nd_cont1_edit.setObjectName("gd_nd_cont1_edit")
        self.horizontalLayout_13.addWidget(self.gd_nd_cont1_edit)
        self.verticalLayout_8.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.gd_nd_cont2_lbl = QtWidgets.QLabel(self.layoutWidget)
        self.gd_nd_cont2_lbl.setObjectName("gd_nd_cont2_lbl")
        self.horizontalLayout_14.addWidget(self.gd_nd_cont2_lbl)
        self.gd_nd_cont2_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.gd_nd_cont2_edit.setObjectName("gd_nd_cont2_edit")
        self.horizontalLayout_14.addWidget(self.gd_nd_cont2_edit)
        self.verticalLayout_8.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_23.addLayout(self.verticalLayout_8)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.gd_nd_cont3_lbl = QtWidgets.QLabel(self.layoutWidget)
        self.gd_nd_cont3_lbl.setObjectName("gd_nd_cont3_lbl")
        self.horizontalLayout_15.addWidget(self.gd_nd_cont3_lbl)
        self.gd_nd_cont3_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.gd_nd_cont3_edit.setObjectName("gd_nd_cont3_edit")
        self.horizontalLayout_15.addWidget(self.gd_nd_cont3_edit)
        self.verticalLayout_7.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.gd_nd_cont4_lbl = QtWidgets.QLabel(self.layoutWidget)
        self.gd_nd_cont4_lbl.setObjectName("gd_nd_cont4_lbl")
        self.horizontalLayout_16.addWidget(self.gd_nd_cont4_lbl)
        self.gd_nd_cont4_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.gd_nd_cont4_edit.setObjectName("gd_nd_cont4_edit")
        self.horizontalLayout_16.addWidget(self.gd_nd_cont4_edit)
        self.verticalLayout_7.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.gd_nd_cont5_lbl = QtWidgets.QLabel(self.layoutWidget)
        self.gd_nd_cont5_lbl.setObjectName("gd_nd_cont5_lbl")
        self.horizontalLayout_17.addWidget(self.gd_nd_cont5_lbl)
        self.gd_nd_cont5_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.gd_nd_cont5_edit.setObjectName("gd_nd_cont5_edit")
        self.horizontalLayout_17.addWidget(self.gd_nd_cont5_edit)
        self.verticalLayout_7.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_23.addLayout(self.verticalLayout_7)
        self.verticalLayout_9.addLayout(self.horizontalLayout_23)
        self.verticalLayout_9.setStretch(0, 1)
        self.verticalLayout_9.setStretch(1, 1)
        self.verticalLayout_9.setStretch(3, 10)
        self.horizontalLayout_24.addLayout(self.verticalLayout_9)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gd_nd_tree = QtWidgets.QTreeWidget(self.layoutWidget)
        self.gd_nd_tree.setObjectName("gd_nd_tree")
        self.gd_nd_tree.headerItem().setText(0, "DoDataIndex")
        self.verticalLayout_4.addWidget(self.gd_nd_tree)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.gd_nd_input_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.gd_nd_input_btn.setObjectName("gd_nd_input_btn")
        self.horizontalLayout_22.addWidget(self.gd_nd_input_btn)
        self.gd_nd_remove_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.gd_nd_remove_btn.setObjectName("gd_nd_remove_btn")
        self.horizontalLayout_22.addWidget(self.gd_nd_remove_btn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_24.addLayout(self.verticalLayout_4)
        self.gd_data_edit_vbox.addLayout(self.horizontalLayout_24)
        self.gd_main_hbox.addLayout(self.gd_data_edit_vbox)
        self.gd_preview_and_edit_vline = QtWidgets.QFrame(self.layoutWidget)
        self.gd_preview_and_edit_vline.setFrameShape(QtWidgets.QFrame.VLine)
        self.gd_preview_and_edit_vline.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.gd_preview_and_edit_vline.setObjectName("gd_preview_and_edit_vline")
        self.gd_main_hbox.addWidget(self.gd_preview_and_edit_vline)
        self.gd_data_preview_vbox = QtWidgets.QVBoxLayout()
        self.gd_data_preview_vbox.setObjectName("gd_data_preview_vbox")
        self.gd_pre_lbl = QtWidgets.QLabel(self.layoutWidget)
        self.gd_pre_lbl.setObjectName("gd_pre_lbl")
        self.gd_data_preview_vbox.addWidget(self.gd_pre_lbl)
        self.gd_pre_edit = QtWidgets.QTextEdit(self.layoutWidget)
        self.gd_pre_edit.setObjectName("gd_pre_edit")
        self.gd_data_preview_vbox.addWidget(self.gd_pre_edit)
        self.gd_preview_create_and_clear_hbox = QtWidgets.QHBoxLayout()
        self.gd_preview_create_and_clear_hbox.setObjectName("gd_preview_create_and_clear_hbox")
        self.gd_pre_create_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.gd_pre_create_btn.setObjectName("gd_pre_create_btn")
        self.gd_preview_create_and_clear_hbox.addWidget(self.gd_pre_create_btn)
        self.gd_pre_clear_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.gd_pre_clear_btn.setObjectName("gd_pre_clear_btn")
        self.gd_preview_create_and_clear_hbox.addWidget(self.gd_pre_clear_btn)
        self.gd_data_preview_vbox.addLayout(self.gd_preview_create_and_clear_hbox)
        self.gd_preview_hline = QtWidgets.QFrame(self.layoutWidget)
        self.gd_preview_hline.setFrameShape(QtWidgets.QFrame.HLine)
        self.gd_preview_hline.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.gd_preview_hline.setObjectName("gd_preview_hline")
        self.gd_data_preview_vbox.addWidget(self.gd_preview_hline)
        self.gd_pre_save_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.gd_pre_save_btn.setObjectName("gd_pre_save_btn")
        self.gd_data_preview_vbox.addWidget(self.gd_pre_save_btn)
        self.gd_main_hbox.addLayout(self.gd_data_preview_vbox)
        self.gd_type_tab.addTab(self.tab, "")
        self.help_data_tab = QtWidgets.QWidget()
        self.help_data_tab.setObjectName("help_data_tab")
        self.layoutWidget1 = QtWidgets.QWidget(self.help_data_tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 1251, 621))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.help_main_hbox = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.help_main_hbox.setContentsMargins(0, 0, 0, 0)
        self.help_main_hbox.setObjectName("help_main_hbox")
        self.verticalLayout_39 = QtWidgets.QVBoxLayout()
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.horizontalLayout_105 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_105.setObjectName("horizontalLayout_105")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.help_tri_lbl = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.help_tri_lbl.sizePolicy().hasHeightForWidth())
        self.help_tri_lbl.setSizePolicy(sizePolicy)
        self.help_tri_lbl.setObjectName("help_tri_lbl")
        self.verticalLayout_13.addWidget(self.help_tri_lbl)
        self.line_18 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.verticalLayout_13.addWidget(self.line_18)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.help_tri_type_lbl = QtWidgets.QLabel(self.layoutWidget1)
        self.help_tri_type_lbl.setObjectName("help_tri_type_lbl")
        self.horizontalLayout_28.addWidget(self.help_tri_type_lbl)
        self.help_tri_type_box = QtWidgets.QComboBox(self.layoutWidget1)
        self.help_tri_type_box.setToolTip("")
        self.help_tri_type_box.setToolTipDuration(-1)
        self.help_tri_type_box.setObjectName("help_tri_type_box")
        self.horizontalLayout_28.addWidget(self.help_tri_type_box)
        self.verticalLayout_13.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.help_tri_cont1_lbl = QtWidgets.QLabel(self.layoutWidget1)
        self.help_tri_cont1_lbl.setObjectName("help_tri_cont1_lbl")
        self.horizontalLayout_29.addWidget(self.help_tri_cont1_lbl)
        self.help_tri_cont1_edit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.help_tri_cont1_edit.setObjectName("help_tri_cont1_edit")
        self.horizontalLayout_29.addWidget(self.help_tri_cont1_edit)
        self.verticalLayout_13.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.help_tri_cont2_lbl = QtWidgets.QLabel(self.layoutWidget1)
        self.help_tri_cont2_lbl.setObjectName("help_tri_cont2_lbl")
        self.horizontalLayout_30.addWidget(self.help_tri_cont2_lbl)
        self.help_tri_cont2_edit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.help_tri_cont2_edit.setText("")
        self.help_tri_cont2_edit.setObjectName("help_tri_cont2_edit")
        self.horizontalLayout_30.addWidget(self.help_tri_cont2_edit)
        self.verticalLayout_13.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.help_tri_cont3_lbl = QtWidgets.QLabel(self.layoutWidget1)
        self.help_tri_cont3_lbl.setObjectName("help_tri_cont3_lbl")
        self.horizontalLayout_31.addWidget(self.help_tri_cont3_lbl)
        self.help_tri_cont3_edit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.help_tri_cont3_edit.setText("")
        self.help_tri_cont3_edit.setObjectName("help_tri_cont3_edit")
        self.horizontalLayout_31.addWidget(self.help_tri_cont3_edit)
        self.verticalLayout_13.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_33.addLayout(self.verticalLayout_13)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.help_tri_data_tree = QtWidgets.QListWidget(self.layoutWidget1)
        self.help_tri_data_tree.setObjectName("help_tri_data_tree")
        self.verticalLayout_12.addWidget(self.help_tri_data_tree)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.help_tri_input_btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.help_tri_input_btn.setObjectName("help_tri_input_btn")
        self.horizontalLayout_32.addWidget(self.help_tri_input_btn)
        self.help_tri_remove_btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.help_tri_remove_btn.setObjectName("help_tri_remove_btn")
        self.horizontalLayout_32.addWidget(self.help_tri_remove_btn)
        self.verticalLayout_12.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_33.addLayout(self.verticalLayout_12)
        self.horizontalLayout_105.addLayout(self.horizontalLayout_33)
        self.line_13 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.horizontalLayout_105.addWidget(self.line_13)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.help_completecond_lbl = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.help_completecond_lbl.sizePolicy().hasHeightForWidth())
        self.help_completecond_lbl.setSizePolicy(sizePolicy)
        self.help_completecond_lbl.setObjectName("help_completecond_lbl")
        self.verticalLayout_14.addWidget(self.help_completecond_lbl)
        self.line_19 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_19.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.verticalLayout_14.addWidget(self.line_19)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.help_cond_type_lbl = QtWidgets.QLabel(self.layoutWidget1)
        self.help_cond_type_lbl.setObjectName("help_cond_type_lbl")
        self.horizontalLayout_35.addWidget(self.help_cond_type_lbl)
        self.help_cond_type_box = QtWidgets.QComboBox(self.layoutWidget1)
        self.help_cond_type_box.setObjectName("help_cond_type_box")
        self.horizontalLayout_35.addWidget(self.help_cond_type_box)
        self.verticalLayout_14.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.help_cond_cont1_lbl = QtWidgets.QLabel(self.layoutWidget1)
        self.help_cond_cont1_lbl.setObjectName("help_cond_cont1_lbl")
        self.horizontalLayout_36.addWidget(self.help_cond_cont1_lbl)
        self.help_cond_cont1_edit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.help_cond_cont1_edit.setObjectName("help_cond_cont1_edit")
        self.horizontalLayout_36.addWidget(self.help_cond_cont1_edit)
        self.verticalLayout_14.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.help_cond_cont2_lbl = QtWidgets.QLabel(self.layoutWidget1)
        self.help_cond_cont2_lbl.setObjectName("help_cond_cont2_lbl")
        self.horizontalLayout_37.addWidget(self.help_cond_cont2_lbl)
        self.help_cond_cont2_edit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.help_cond_cont2_edit.setText("")
        self.help_cond_cont2_edit.setObjectName("help_cond_cont2_edit")
        self.horizontalLayout_37.addWidget(self.help_cond_cont2_edit)
        self.verticalLayout_14.addLayout(self.horizontalLayout_37)
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.help_cond_cont3_lbl = QtWidgets.QLabel(self.layoutWidget1)
        self.help_cond_cont3_lbl.setObjectName("help_cond_cont3_lbl")
        self.horizontalLayout_38.addWidget(self.help_cond_cont3_lbl)
        self.help_cond_cont3_edit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.help_cond_cont3_edit.setText("")
        self.help_cond_cont3_edit.setObjectName("help_cond_cont3_edit")
        self.horizontalLayout_38.addWidget(self.help_cond_cont3_edit)
        self.verticalLayout_14.addLayout(self.horizontalLayout_38)
        self.horizontalLayout_34.addLayout(self.verticalLayout_14)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.help_cond_data_tree = QtWidgets.QListWidget(self.layoutWidget1)
        self.help_cond_data_tree.setObjectName("help_cond_data_tree")
        self.verticalLayout_15.addWidget(self.help_cond_data_tree)
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.help_cond_input_btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.help_cond_input_btn.setObjectName("help_cond_input_btn")
        self.horizontalLayout_39.addWidget(self.help_cond_input_btn)
        self.help_cond_remove_btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.help_cond_remove_btn.setObjectName("help_cond_remove_btn")
        self.horizontalLayout_39.addWidget(self.help_cond_remove_btn)
        self.verticalLayout_15.addLayout(self.horizontalLayout_39)
        self.horizontalLayout_34.addLayout(self.verticalLayout_15)
        self.horizontalLayout_105.addLayout(self.horizontalLayout_34)
        self.verticalLayout_39.addLayout(self.horizontalLayout_105)
        self.line_15 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.verticalLayout_39.addWidget(self.line_15)
        self.horizontalLayout_106 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_106.setObjectName("horizontalLayout_106")
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.help_pre_lbl = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.help_pre_lbl.sizePolicy().hasHeightForWidth())
        self.help_pre_lbl.setSizePolicy(sizePolicy)
        self.help_pre_lbl.setObjectName("help_pre_lbl")
        self.verticalLayout_16.addWidget(self.help_pre_lbl)
        self.line_20 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_20.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.verticalLayout_16.addWidget(self.line_20)
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.help_pre_type_lbl = QtWidgets.QLabel(self.layoutWidget1)
        self.help_pre_type_lbl.setObjectName("help_pre_type_lbl")
        self.horizontalLayout_41.addWidget(self.help_pre_type_lbl)
        self.help_pre_type_boox = QtWidgets.QComboBox(self.layoutWidget1)
        self.help_pre_type_boox.setObjectName("help_pre_type_boox")
        self.horizontalLayout_41.addWidget(self.help_pre_type_boox)
        self.verticalLayout_16.addLayout(self.horizontalLayout_41)
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.help_pre_cont1_lbl = QtWidgets.QLabel(self.layoutWidget1)
        self.help_pre_cont1_lbl.setObjectName("help_pre_cont1_lbl")
        self.horizontalLayout_42.addWidget(self.help_pre_cont1_lbl)
        self.help_pre_cont1_edit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.help_pre_cont1_edit.setObjectName("help_pre_cont1_edit")
        self.horizontalLayout_42.addWidget(self.help_pre_cont1_edit)
        self.verticalLayout_16.addLayout(self.horizontalLayout_42)
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.help_pre_cont2_lbl = QtWidgets.QLabel(self.layoutWidget1)
        self.help_pre_cont2_lbl.setObjectName("help_pre_cont2_lbl")
        self.horizontalLayout_43.addWidget(self.help_pre_cont2_lbl)
        self.help_pre_cont2_edit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.help_pre_cont2_edit.setText("")
        self.help_pre_cont2_edit.setObjectName("help_pre_cont2_edit")
        self.horizontalLayout_43.addWidget(self.help_pre_cont2_edit)
        self.verticalLayout_16.addLayout(self.horizontalLayout_43)
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.help_pre_cont3_lbl = QtWidgets.QLabel(self.layoutWidget1)
        self.help_pre_cont3_lbl.setObjectName("help_pre_cont3_lbl")
        self.horizontalLayout_44.addWidget(self.help_pre_cont3_lbl)
        self.help_pre_cont3_edit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.help_pre_cont3_edit.setText("")
        self.help_pre_cont3_edit.setObjectName("help_pre_cont3_edit")
        self.horizontalLayout_44.addWidget(self.help_pre_cont3_edit)
        self.verticalLayout_16.addLayout(self.horizontalLayout_44)
        self.horizontalLayout_40.addLayout(self.verticalLayout_16)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.help_pre_data_tree = QtWidgets.QListWidget(self.layoutWidget1)
        self.help_pre_data_tree.setObjectName("help_pre_data_tree")
        self.verticalLayout_17.addWidget(self.help_pre_data_tree)
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.help_pre_input_btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.help_pre_input_btn.setObjectName("help_pre_input_btn")
        self.horizontalLayout_45.addWidget(self.help_pre_input_btn)
        self.help_pre_remove_btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.help_pre_remove_btn.setObjectName("help_pre_remove_btn")
        self.horizontalLayout_45.addWidget(self.help_pre_remove_btn)
        self.verticalLayout_17.addLayout(self.horizontalLayout_45)
        self.horizontalLayout_40.addLayout(self.verticalLayout_17)
        self.horizontalLayout_106.addLayout(self.horizontalLayout_40)
        self.line_14 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.horizontalLayout_106.addWidget(self.line_14)
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.help_do_data_lbl = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.help_do_data_lbl.sizePolicy().hasHeightForWidth())
        self.help_do_data_lbl.setSizePolicy(sizePolicy)
        self.help_do_data_lbl.setObjectName("help_do_data_lbl")
        self.verticalLayout_18.addWidget(self.help_do_data_lbl)
        self.line_21 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_21.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.verticalLayout_18.addWidget(self.line_21)
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.help_do_type_lbl = QtWidgets.QLabel(self.layoutWidget1)
        self.help_do_type_lbl.setObjectName("help_do_type_lbl")
        self.horizontalLayout_47.addWidget(self.help_do_type_lbl)
        self.help_do_type_box = QtWidgets.QComboBox(self.layoutWidget1)
        self.help_do_type_box.setObjectName("help_do_type_box")
        self.horizontalLayout_47.addWidget(self.help_do_type_box)
        self.verticalLayout_18.addLayout(self.horizontalLayout_47)
        self.horizontalLayout_48 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_48.setObjectName("horizontalLayout_48")
        self.help_do_cont1_lbl = QtWidgets.QLabel(self.layoutWidget1)
        self.help_do_cont1_lbl.setObjectName("help_do_cont1_lbl")
        self.horizontalLayout_48.addWidget(self.help_do_cont1_lbl)
        self.help_do_cont1_edit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.help_do_cont1_edit.setObjectName("help_do_cont1_edit")
        self.horizontalLayout_48.addWidget(self.help_do_cont1_edit)
        self.verticalLayout_18.addLayout(self.horizontalLayout_48)
        self.horizontalLayout_49 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_49.setObjectName("horizontalLayout_49")
        self.help_do_cont2_lbl = QtWidgets.QLabel(self.layoutWidget1)
        self.help_do_cont2_lbl.setObjectName("help_do_cont2_lbl")
        self.horizontalLayout_49.addWidget(self.help_do_cont2_lbl)
        self.help_do_cont2_edit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.help_do_cont2_edit.setText("")
        self.help_do_cont2_edit.setObjectName("help_do_cont2_edit")
        self.horizontalLayout_49.addWidget(self.help_do_cont2_edit)
        self.verticalLayout_18.addLayout(self.horizontalLayout_49)
        self.horizontalLayout_50 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_50.setObjectName("horizontalLayout_50")
        self.help_do_cont3_lbl = QtWidgets.QLabel(self.layoutWidget1)
        self.help_do_cont3_lbl.setObjectName("help_do_cont3_lbl")
        self.horizontalLayout_50.addWidget(self.help_do_cont3_lbl)
        self.lhelp_do_cont3_edit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lhelp_do_cont3_edit.setText("")
        self.lhelp_do_cont3_edit.setObjectName("lhelp_do_cont3_edit")
        self.horizontalLayout_50.addWidget(self.lhelp_do_cont3_edit)
        self.verticalLayout_18.addLayout(self.horizontalLayout_50)
        self.horizontalLayout_103 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_103.setObjectName("horizontalLayout_103")
        self.help_do_cont4_lbl = QtWidgets.QLabel(self.layoutWidget1)
        self.help_do_cont4_lbl.setObjectName("help_do_cont4_lbl")
        self.horizontalLayout_103.addWidget(self.help_do_cont4_lbl)
        self.help_do_cont4_edit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.help_do_cont4_edit.setText("")
        self.help_do_cont4_edit.setObjectName("help_do_cont4_edit")
        self.horizontalLayout_103.addWidget(self.help_do_cont4_edit)
        self.verticalLayout_18.addLayout(self.horizontalLayout_103)
        self.horizontalLayout_104 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_104.setObjectName("horizontalLayout_104")
        self.help_do_cont5_lbl = QtWidgets.QLabel(self.layoutWidget1)
        self.help_do_cont5_lbl.setObjectName("help_do_cont5_lbl")
        self.horizontalLayout_104.addWidget(self.help_do_cont5_lbl)
        self.help_do_cont5_edit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.help_do_cont5_edit.setText("")
        self.help_do_cont5_edit.setObjectName("help_do_cont5_edit")
        self.horizontalLayout_104.addWidget(self.help_do_cont5_edit)
        self.verticalLayout_18.addLayout(self.horizontalLayout_104)
        self.horizontalLayout_46.addLayout(self.verticalLayout_18)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.help_do_tree = QtWidgets.QListWidget(self.layoutWidget1)
        self.help_do_tree.setObjectName("help_do_tree")
        self.verticalLayout_19.addWidget(self.help_do_tree)
        self.horizontalLayout_51 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_51.setObjectName("horizontalLayout_51")
        self.help_do_input_btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.help_do_input_btn.setObjectName("help_do_input_btn")
        self.horizontalLayout_51.addWidget(self.help_do_input_btn)
        self.help_do_remove_btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.help_do_remove_btn.setObjectName("help_do_remove_btn")
        self.horizontalLayout_51.addWidget(self.help_do_remove_btn)
        self.verticalLayout_19.addLayout(self.horizontalLayout_51)
        self.horizontalLayout_46.addLayout(self.verticalLayout_19)
        self.horizontalLayout_106.addLayout(self.horizontalLayout_46)
        self.verticalLayout_39.addLayout(self.horizontalLayout_106)
        self.help_main_hbox.addLayout(self.verticalLayout_39)
        self.line_17 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_17.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.help_main_hbox.addWidget(self.line_17)
        self.verticalLayout_40 = QtWidgets.QVBoxLayout()
        self.verticalLayout_40.setObjectName("verticalLayout_40")
        self.help_preview_lbl = QtWidgets.QLabel(self.layoutWidget1)
        self.help_preview_lbl.setObjectName("help_preview_lbl")
        self.verticalLayout_40.addWidget(self.help_preview_lbl)
        self.help_preview_edit = QtWidgets.QTextEdit(self.layoutWidget1)
        self.help_preview_edit.setObjectName("help_preview_edit")
        self.verticalLayout_40.addWidget(self.help_preview_edit)
        self.horizontalLayout_107 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_107.setObjectName("horizontalLayout_107")
        self.help_create_btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.help_create_btn.setObjectName("help_create_btn")
        self.horizontalLayout_107.addWidget(self.help_create_btn)
        self.help_clear_btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.help_clear_btn.setObjectName("help_clear_btn")
        self.horizontalLayout_107.addWidget(self.help_clear_btn)
        self.verticalLayout_40.addLayout(self.horizontalLayout_107)
        self.line_16 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.verticalLayout_40.addWidget(self.line_16)
        self.help_save_btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.help_save_btn.setObjectName("help_save_btn")
        self.verticalLayout_40.addWidget(self.help_save_btn)
        self.help_main_hbox.addLayout(self.verticalLayout_40)
        self.gd_type_tab.addTab(self.help_data_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave_s = QtWidgets.QAction(MainWindow)
        self.actionSave_s.setObjectName("actionSave_s")
        self.actionQuit_q = QtWidgets.QAction(MainWindow)
        self.actionQuit_q.setObjectName("actionQuit_q")
        self.menu.addAction(self.actionSave_s)
        self.menu.addSeparator()
        self.menu.addAction(self.actionQuit_q)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.gd_type_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "引导工具Ver3.0"))
        self.gd_name_lbl.setText(_translate("MainWindow", "GuideName"))
        self.gd_tri_lbl.setText(_translate("MainWindow", "TriggerType"))
        self.gd_tri_cont1_lbl.setText(_translate("MainWindow", "content1"))
        self.gd_tri_cont2_lbl.setText(_translate("MainWindow", "content2"))
        self.gd_tri_cont3_lbl.setText(_translate("MainWindow", "content3"))
        self.gd_tri_input_btn.setText(_translate("MainWindow", "插入"))
        self.gd_tri_remove_btn.setText(_translate("MainWindow", "移除"))
        self.gd_cond_isenable_check.setText(_translate("MainWindow", "IsEnable"))
        self.gd_cond_type_lbl.setText(_translate("MainWindow", "ConditionType"))
        self.gd_cond_cont1_lbl.setText(_translate("MainWindow", "content1"))
        self.gd_cond_cont2_lbl.setText(_translate("MainWindow", "content2"))
        self.gd_cond_cont3_lbl.setText(_translate("MainWindow", "content3"))
        self.gd_cond_input_btn.setText(_translate("MainWindow", "插入"))
        self.gd_cond_remove_btn.setText(_translate("MainWindow", "移除"))
        self.gd_nd_isclick_lbl.setText(_translate("MainWindow", "IsClickToNext"))
        self.gd_nd_isclick_box.setItemText(0, _translate("MainWindow", "false"))
        self.gd_nd_isclick_box.setItemText(1, _translate("MainWindow", "true"))
        self.gd_nd_isauto_lbl.setText(_translate("MainWindow", "IsAutoToNext"))
        self.gd_nd_dotype_lbl.setText(_translate("MainWindow", "DoType"))
        self.gd_nd_cont1_lbl.setText(_translate("MainWindow", "content1"))
        self.gd_nd_cont2_lbl.setText(_translate("MainWindow", "content2"))
        self.gd_nd_cont3_lbl.setText(_translate("MainWindow", "content3"))
        self.gd_nd_cont4_lbl.setText(_translate("MainWindow", "content4"))
        self.gd_nd_cont5_lbl.setText(_translate("MainWindow", "content5"))
        self.gd_nd_input_btn.setText(_translate("MainWindow", "插入"))
        self.gd_nd_remove_btn.setText(_translate("MainWindow", "移除"))
        self.gd_pre_lbl.setText(_translate("MainWindow", "PreView"))
        self.gd_pre_create_btn.setText(_translate("MainWindow", "生成"))
        self.gd_pre_clear_btn.setText(_translate("MainWindow", "清空"))
        self.gd_pre_save_btn.setText(_translate("MainWindow", "保存"))
        self.gd_type_tab.setTabText(self.gd_type_tab.indexOf(self.tab), _translate("MainWindow", "GuideData"))
        self.help_tri_lbl.setText(_translate("MainWindow", "Triggers"))
        self.help_tri_type_lbl.setText(_translate("MainWindow", "TriggerType"))
        self.help_tri_cont1_lbl.setText(_translate("MainWindow", "content1"))
        self.help_tri_cont2_lbl.setText(_translate("MainWindow", "content2"))
        self.help_tri_cont3_lbl.setText(_translate("MainWindow", "content3"))
        self.help_tri_input_btn.setText(_translate("MainWindow", "插入"))
        self.help_tri_remove_btn.setText(_translate("MainWindow", "删除"))
        self.help_completecond_lbl.setText(_translate("MainWindow", "CompleteConditions"))
        self.help_cond_type_lbl.setText(_translate("MainWindow", "ConditionType"))
        self.help_cond_cont1_lbl.setText(_translate("MainWindow", "content1"))
        self.help_cond_cont2_lbl.setText(_translate("MainWindow", "content2"))
        self.help_cond_cont3_lbl.setText(_translate("MainWindow", "content3"))
        self.help_cond_input_btn.setText(_translate("MainWindow", "插入"))
        self.help_cond_remove_btn.setText(_translate("MainWindow", "删除"))
        self.help_pre_lbl.setText(_translate("MainWindow", "Preconditions"))
        self.help_pre_type_lbl.setText(_translate("MainWindow", "ConditionType"))
        self.help_pre_cont1_lbl.setText(_translate("MainWindow", "content1"))
        self.help_pre_cont2_lbl.setText(_translate("MainWindow", "content2"))
        self.help_pre_cont3_lbl.setText(_translate("MainWindow", "content3"))
        self.help_pre_input_btn.setText(_translate("MainWindow", "插入"))
        self.help_pre_remove_btn.setText(_translate("MainWindow", "删除"))
        self.help_do_data_lbl.setText(_translate("MainWindow", "DoData"))
        self.help_do_type_lbl.setText(_translate("MainWindow", "DoType"))
        self.help_do_cont1_lbl.setText(_translate("MainWindow", "content1"))
        self.help_do_cont2_lbl.setText(_translate("MainWindow", "content2"))
        self.help_do_cont3_lbl.setText(_translate("MainWindow", "content3"))
        self.help_do_cont4_lbl.setText(_translate("MainWindow", "content4"))
        self.help_do_cont5_lbl.setText(_translate("MainWindow", "content5"))
        self.help_do_input_btn.setText(_translate("MainWindow", "插入"))
        self.help_do_remove_btn.setText(_translate("MainWindow", "删除"))
        self.help_preview_lbl.setText(_translate("MainWindow", "PreView"))
        self.help_create_btn.setText(_translate("MainWindow", "生成"))
        self.help_clear_btn.setText(_translate("MainWindow", "清空"))
        self.help_save_btn.setText(_translate("MainWindow", "保存"))
        self.gd_type_tab.setTabText(self.gd_type_tab.indexOf(self.help_data_tab), _translate("MainWindow", "HelpData"))
        self.menu.setTitle(_translate("MainWindow", "菜单"))
        self.actionSave_s.setText(_translate("MainWindow", "Save(&s)"))
        self.actionQuit_q.setText(_translate("MainWindow", "Quit(&q)"))
