# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GDToolLayout.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(850, 580)
        MainWindow.setMinimumSize(QtCore.QSize(850, 580))
        MainWindow.setMaximumSize(QtCore.QSize(850, 580))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tab_GDfile_select = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_GDfile_select.setGeometry(QtCore.QRect(0, 0, 461, 551))
        self.tab_GDfile_select.setStyleSheet("")
        self.tab_GDfile_select.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tab_GDfile_select.setObjectName("tab_GDfile_select")
        self.tab_main = QtWidgets.QWidget()
        self.tab_main.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_main.sizePolicy().hasHeightForWidth())
        self.tab_main.setSizePolicy(sizePolicy)
        self.tab_main.setObjectName("tab_main")
        self.tab_gdtype_select = QtWidgets.QTabWidget(self.tab_main)
        self.tab_gdtype_select.setGeometry(QtCore.QRect(-10, 40, 471, 481))
        self.tab_gdtype_select.setStyleSheet("tab{width:120}")
        self.tab_gdtype_select.setTabPosition(QtWidgets.QTabWidget.South)
        self.tab_gdtype_select.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tab_gdtype_select.setObjectName("tab_gdtype_select")
        self.tab_gd_triggers = QtWidgets.QWidget()
        self.tab_gd_triggers.setObjectName("tab_gd_triggers")
        self.lbl_gd_tri = QtWidgets.QLabel(self.tab_gd_triggers)
        self.lbl_gd_tri.setGeometry(QtCore.QRect(10, 1, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_gd_tri.setFont(font)
        self.lbl_gd_tri.setObjectName("lbl_gd_tri")
        self.line_gd_tri1 = QtWidgets.QFrame(self.tab_gd_triggers)
        self.line_gd_tri1.setGeometry(QtCore.QRect(10, 20, 451, 16))
        self.line_gd_tri1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_gd_tri1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_gd_tri1.setObjectName("line_gd_tri1")
        self.lbl_gd_tri_type = QtWidgets.QLabel(self.tab_gd_triggers)
        self.lbl_gd_tri_type.setGeometry(QtCore.QRect(10, 40, 61, 16))
        self.lbl_gd_tri_type.setObjectName("lbl_gd_tri_type")
        self.cbox_gd_tri_type = QtWidgets.QComboBox(self.tab_gd_triggers)
        self.cbox_gd_tri_type.setGeometry(QtCore.QRect(70, 38, 381, 22))
        self.cbox_gd_tri_type.setObjectName("cbox_gd_tri_type")
        self.lbl_gd_tri_cont1 = QtWidgets.QLabel(self.tab_gd_triggers)
        self.lbl_gd_tri_cont1.setGeometry(QtCore.QRect(10, 95, 54, 12))
        self.lbl_gd_tri_cont1.setObjectName("lbl_gd_tri_cont1")
        self.lbl_gd_tri_cont2 = QtWidgets.QLabel(self.tab_gd_triggers)
        self.lbl_gd_tri_cont2.setGeometry(QtCore.QRect(10, 125, 54, 12))
        self.lbl_gd_tri_cont2.setObjectName("lbl_gd_tri_cont2")
        self.lbl_gd_tri_cont3 = QtWidgets.QLabel(self.tab_gd_triggers)
        self.lbl_gd_tri_cont3.setGeometry(QtCore.QRect(10, 155, 54, 12))
        self.lbl_gd_tri_cont3.setObjectName("lbl_gd_tri_cont3")
        self.le_gd_tri_cont1 = QtWidgets.QLineEdit(self.tab_gd_triggers)
        self.le_gd_tri_cont1.setGeometry(QtCore.QRect(70, 90, 381, 20))
        self.le_gd_tri_cont1.setObjectName("le_gd_tri_cont1")
        self.le_gd_tri_cont2 = QtWidgets.QLineEdit(self.tab_gd_triggers)
        self.le_gd_tri_cont2.setGeometry(QtCore.QRect(70, 120, 381, 20))
        self.le_gd_tri_cont2.setObjectName("le_gd_tri_cont2")
        self.le_gd_tri_cont3 = QtWidgets.QLineEdit(self.tab_gd_triggers)
        self.le_gd_tri_cont3.setGeometry(QtCore.QRect(70, 150, 381, 20))
        self.le_gd_tri_cont3.setObjectName("le_gd_tri_cont3")
        self.tree_gd_tri = QtWidgets.QTreeWidget(self.tab_gd_triggers)
        self.tree_gd_tri.setGeometry(QtCore.QRect(10, 220, 341, 231))
        self.tree_gd_tri.setObjectName("tree_gd_tri")
        self.line_gd_tri2 = QtWidgets.QFrame(self.tab_gd_triggers)
        self.line_gd_tri2.setGeometry(QtCore.QRect(10, 65, 451, 16))
        self.line_gd_tri2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_gd_tri2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_gd_tri2.setObjectName("line_gd_tri2")
        self.line_gd_tri3 = QtWidgets.QFrame(self.tab_gd_triggers)
        self.line_gd_tri3.setGeometry(QtCore.QRect(10, 180, 451, 16))
        self.line_gd_tri3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_gd_tri3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_gd_tri3.setObjectName("line_gd_tri3")
        self.lbl_gd_tri_list = QtWidgets.QLabel(self.tab_gd_triggers)
        self.lbl_gd_tri_list.setGeometry(QtCore.QRect(10, 195, 81, 16))
        self.lbl_gd_tri_list.setObjectName("lbl_gd_tri_list")
        self.btn_gd_tri_insert = QtWidgets.QPushButton(self.tab_gd_triggers)
        self.btn_gd_tri_insert.setGeometry(QtCore.QRect(370, 220, 75, 23))
        self.btn_gd_tri_insert.setObjectName("btn_gd_tri_insert")
        self.btn_gd_tri_del = QtWidgets.QPushButton(self.tab_gd_triggers)
        self.btn_gd_tri_del.setGeometry(QtCore.QRect(370, 260, 75, 23))
        self.btn_gd_tri_del.setObjectName("btn_gd_tri_del")
        self.btn_gd_tri_upmove = QtWidgets.QPushButton(self.tab_gd_triggers)
        self.btn_gd_tri_upmove.setGeometry(QtCore.QRect(370, 300, 75, 23))
        self.btn_gd_tri_upmove.setObjectName("btn_gd_tri_upmove")
        self.btn_gd_tri_downmove = QtWidgets.QPushButton(self.tab_gd_triggers)
        self.btn_gd_tri_downmove.setGeometry(QtCore.QRect(370, 340, 75, 23))
        self.btn_gd_tri_downmove.setObjectName("btn_gd_tri_downmove")
        self.btn_gd_tri_clear = QtWidgets.QPushButton(self.tab_gd_triggers)
        self.btn_gd_tri_clear.setGeometry(QtCore.QRect(370, 380, 75, 23))
        self.btn_gd_tri_clear.setObjectName("btn_gd_tri_clear")
        self.tab_gdtype_select.addTab(self.tab_gd_triggers, "")
        self.tab_gd_preconditions = QtWidgets.QWidget()
        self.tab_gd_preconditions.setObjectName("tab_gd_preconditions")
        self.lbl_gd_pre = QtWidgets.QLabel(self.tab_gd_preconditions)
        self.lbl_gd_pre.setGeometry(QtCore.QRect(10, 1, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_gd_pre.setFont(font)
        self.lbl_gd_pre.setObjectName("lbl_gd_pre")
        self.tree_gd_pre = QtWidgets.QTreeWidget(self.tab_gd_preconditions)
        self.tree_gd_pre.setGeometry(QtCore.QRect(10, 220, 341, 231))
        self.tree_gd_pre.setObjectName("tree_gd_pre")
        self.tree_gd_pre.headerItem().setText(0, "Preconditions")
        self.line_gd_pre3 = QtWidgets.QFrame(self.tab_gd_preconditions)
        self.line_gd_pre3.setGeometry(QtCore.QRect(10, 180, 451, 16))
        self.line_gd_pre3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_gd_pre3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_gd_pre3.setObjectName("line_gd_pre3")
        self.btn_gd_pre_upmove = QtWidgets.QPushButton(self.tab_gd_preconditions)
        self.btn_gd_pre_upmove.setGeometry(QtCore.QRect(370, 300, 75, 23))
        self.btn_gd_pre_upmove.setObjectName("btn_gd_pre_upmove")
        self.line_gd_pre1 = QtWidgets.QFrame(self.tab_gd_preconditions)
        self.line_gd_pre1.setGeometry(QtCore.QRect(10, 20, 451, 16))
        self.line_gd_pre1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_gd_pre1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_gd_pre1.setObjectName("line_gd_pre1")
        self.btn_gd_pre_downmove = QtWidgets.QPushButton(self.tab_gd_preconditions)
        self.btn_gd_pre_downmove.setGeometry(QtCore.QRect(370, 340, 75, 23))
        self.btn_gd_pre_downmove.setObjectName("btn_gd_pre_downmove")
        self.le_gd_pre_cont3 = QtWidgets.QLineEdit(self.tab_gd_preconditions)
        self.le_gd_pre_cont3.setGeometry(QtCore.QRect(70, 150, 381, 20))
        self.le_gd_pre_cont3.setObjectName("le_gd_pre_cont3")
        self.lbl_gd_pre_cont1 = QtWidgets.QLabel(self.tab_gd_preconditions)
        self.lbl_gd_pre_cont1.setGeometry(QtCore.QRect(10, 95, 54, 12))
        self.lbl_gd_pre_cont1.setObjectName("lbl_gd_pre_cont1")
        self.cbox_gd_pre_type = QtWidgets.QComboBox(self.tab_gd_preconditions)
        self.cbox_gd_pre_type.setGeometry(QtCore.QRect(70, 38, 381, 22))
        self.cbox_gd_pre_type.setObjectName("cbox_gd_pre_type")
        self.btn_gd_pre_del = QtWidgets.QPushButton(self.tab_gd_preconditions)
        self.btn_gd_pre_del.setGeometry(QtCore.QRect(370, 260, 75, 23))
        self.btn_gd_pre_del.setObjectName("btn_gd_pre_del")
        self.line_gd_pre2 = QtWidgets.QFrame(self.tab_gd_preconditions)
        self.line_gd_pre2.setGeometry(QtCore.QRect(10, 65, 451, 16))
        self.line_gd_pre2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_gd_pre2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_gd_pre2.setObjectName("line_gd_pre2")
        self.btn_gd_pre_clear = QtWidgets.QPushButton(self.tab_gd_preconditions)
        self.btn_gd_pre_clear.setGeometry(QtCore.QRect(370, 380, 75, 23))
        self.btn_gd_pre_clear.setObjectName("btn_gd_pre_clear")
        self.le_gd_pre_cont1 = QtWidgets.QLineEdit(self.tab_gd_preconditions)
        self.le_gd_pre_cont1.setGeometry(QtCore.QRect(70, 90, 381, 20))
        self.le_gd_pre_cont1.setObjectName("le_gd_pre_cont1")
        self.lbl_gd_pre_type = QtWidgets.QLabel(self.tab_gd_preconditions)
        self.lbl_gd_pre_type.setGeometry(QtCore.QRect(10, 40, 61, 16))
        self.lbl_gd_pre_type.setObjectName("lbl_gd_pre_type")
        self.lbl_gd_pre_list = QtWidgets.QLabel(self.tab_gd_preconditions)
        self.lbl_gd_pre_list.setGeometry(QtCore.QRect(10, 195, 81, 16))
        self.lbl_gd_pre_list.setObjectName("lbl_gd_pre_list")
        self.le_gd_pre_cont2 = QtWidgets.QLineEdit(self.tab_gd_preconditions)
        self.le_gd_pre_cont2.setGeometry(QtCore.QRect(70, 120, 381, 20))
        self.le_gd_pre_cont2.setObjectName("le_gd_pre_cont2")
        self.lbl_gd_pre_cont2 = QtWidgets.QLabel(self.tab_gd_preconditions)
        self.lbl_gd_pre_cont2.setGeometry(QtCore.QRect(10, 125, 54, 12))
        self.lbl_gd_pre_cont2.setObjectName("lbl_gd_pre_cont2")
        self.btn_gd_pre_insert = QtWidgets.QPushButton(self.tab_gd_preconditions)
        self.btn_gd_pre_insert.setGeometry(QtCore.QRect(370, 220, 75, 23))
        self.btn_gd_pre_insert.setObjectName("btn_gd_pre_insert")
        self.lbl_gd_pre_cont3 = QtWidgets.QLabel(self.tab_gd_preconditions)
        self.lbl_gd_pre_cont3.setGeometry(QtCore.QRect(10, 155, 54, 12))
        self.lbl_gd_pre_cont3.setObjectName("lbl_gd_pre_cont3")
        self.tab_gdtype_select.addTab(self.tab_gd_preconditions, "")
        self.tab_gd_nodedata = QtWidgets.QWidget()
        self.tab_gd_nodedata.setObjectName("tab_gd_nodedata")
        self.lbl_gd_do_cont2 = QtWidgets.QLabel(self.tab_gd_nodedata)
        self.lbl_gd_do_cont2.setGeometry(QtCore.QRect(10, 145, 54, 12))
        self.lbl_gd_do_cont2.setObjectName("lbl_gd_do_cont2")
        self.btn_gd_do_insert_big = QtWidgets.QPushButton(self.tab_gd_nodedata)
        self.btn_gd_do_insert_big.setGeometry(QtCore.QRect(370, 280, 75, 23))
        self.btn_gd_do_insert_big.setObjectName("btn_gd_do_insert_big")
        self.line_gd_do3 = QtWidgets.QFrame(self.tab_gd_nodedata)
        self.line_gd_do3.setGeometry(QtCore.QRect(10, 249, 451, 16))
        self.line_gd_do3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_gd_do3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_gd_do3.setObjectName("line_gd_do3")
        self.le_gd_do_cont1 = QtWidgets.QLineEdit(self.tab_gd_nodedata)
        self.le_gd_do_cont1.setGeometry(QtCore.QRect(70, 110, 381, 20))
        self.le_gd_do_cont1.setObjectName("le_gd_do_cont1")
        self.cbox_gd_do_type = QtWidgets.QComboBox(self.tab_gd_nodedata)
        self.cbox_gd_do_type.setGeometry(QtCore.QRect(70, 80, 381, 22))
        self.cbox_gd_do_type.setObjectName("cbox_gd_do_type")
        self.le_gd_do_cont2 = QtWidgets.QLineEdit(self.tab_gd_nodedata)
        self.le_gd_do_cont2.setGeometry(QtCore.QRect(70, 140, 381, 20))
        self.le_gd_do_cont2.setObjectName("le_gd_do_cont2")
        self.lbl_gd_do_type = QtWidgets.QLabel(self.tab_gd_nodedata)
        self.lbl_gd_do_type.setGeometry(QtCore.QRect(10, 82, 61, 16))
        self.lbl_gd_do_type.setObjectName("lbl_gd_do_type")
        self.line_gd_do1 = QtWidgets.QFrame(self.tab_gd_nodedata)
        self.line_gd_do1.setGeometry(QtCore.QRect(10, 19, 451, 16))
        self.line_gd_do1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_gd_do1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_gd_do1.setObjectName("line_gd_do1")
        self.lbl_gd_do_list = QtWidgets.QLabel(self.tab_gd_nodedata)
        self.lbl_gd_do_list.setGeometry(QtCore.QRect(10, 260, 81, 16))
        self.lbl_gd_do_list.setObjectName("lbl_gd_do_list")
        self.lbl_gd_do_cont3 = QtWidgets.QLabel(self.tab_gd_nodedata)
        self.lbl_gd_do_cont3.setGeometry(QtCore.QRect(10, 175, 54, 12))
        self.lbl_gd_do_cont3.setObjectName("lbl_gd_do_cont3")
        self.btn_gd_do_downmove = QtWidgets.QPushButton(self.tab_gd_nodedata)
        self.btn_gd_do_downmove.setGeometry(QtCore.QRect(370, 400, 75, 23))
        self.btn_gd_do_downmove.setObjectName("btn_gd_do_downmove")
        self.btn_gd_do_clear = QtWidgets.QPushButton(self.tab_gd_nodedata)
        self.btn_gd_do_clear.setGeometry(QtCore.QRect(370, 430, 75, 23))
        self.btn_gd_do_clear.setObjectName("btn_gd_do_clear")
        self.btn_gd_do_del = QtWidgets.QPushButton(self.tab_gd_nodedata)
        self.btn_gd_do_del.setGeometry(QtCore.QRect(370, 340, 75, 23))
        self.btn_gd_do_del.setObjectName("btn_gd_do_del")
        self.lbl_gd_do_cont1 = QtWidgets.QLabel(self.tab_gd_nodedata)
        self.lbl_gd_do_cont1.setGeometry(QtCore.QRect(10, 115, 54, 12))
        self.lbl_gd_do_cont1.setObjectName("lbl_gd_do_cont1")
        self.btn_gd_del_upmove = QtWidgets.QPushButton(self.tab_gd_nodedata)
        self.btn_gd_del_upmove.setGeometry(QtCore.QRect(370, 370, 75, 23))
        self.btn_gd_del_upmove.setObjectName("btn_gd_del_upmove")
        self.le_gd_do_cont3 = QtWidgets.QLineEdit(self.tab_gd_nodedata)
        self.le_gd_do_cont3.setGeometry(QtCore.QRect(70, 170, 381, 20))
        self.le_gd_do_cont3.setObjectName("le_gd_do_cont3")
        self.tree_gd_do = QtWidgets.QTreeWidget(self.tab_gd_nodedata)
        self.tree_gd_do.setGeometry(QtCore.QRect(10, 279, 341, 171))
        self.tree_gd_do.setObjectName("tree_gd_do")
        self.tree_gd_do.headerItem().setText(0, "NodeData")
        self.lbl_gd_nd = QtWidgets.QLabel(self.tab_gd_nodedata)
        self.lbl_gd_nd.setGeometry(QtCore.QRect(10, 0, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_gd_nd.setFont(font)
        self.lbl_gd_nd.setObjectName("lbl_gd_nd")
        self.btn_gd_do_insert_small = QtWidgets.QPushButton(self.tab_gd_nodedata)
        self.btn_gd_do_insert_small.setGeometry(QtCore.QRect(370, 310, 75, 23))
        self.btn_gd_do_insert_small.setObjectName("btn_gd_do_insert_small")
        self.lbl_gd_do_cont4 = QtWidgets.QLabel(self.tab_gd_nodedata)
        self.lbl_gd_do_cont4.setGeometry(QtCore.QRect(10, 205, 54, 12))
        self.lbl_gd_do_cont4.setObjectName("lbl_gd_do_cont4")
        self.le_gd_do_cont4 = QtWidgets.QLineEdit(self.tab_gd_nodedata)
        self.le_gd_do_cont4.setGeometry(QtCore.QRect(70, 200, 381, 20))
        self.le_gd_do_cont4.setObjectName("le_gd_do_cont4")
        self.le_gd_do_cont5 = QtWidgets.QLineEdit(self.tab_gd_nodedata)
        self.le_gd_do_cont5.setGeometry(QtCore.QRect(70, 230, 381, 20))
        self.le_gd_do_cont5.setObjectName("le_gd_do_cont5")
        self.lbl_gd_do_cont5 = QtWidgets.QLabel(self.tab_gd_nodedata)
        self.lbl_gd_do_cont5.setGeometry(QtCore.QRect(10, 235, 54, 12))
        self.lbl_gd_do_cont5.setObjectName("lbl_gd_do_cont5")
        self.line_gd_do2 = QtWidgets.QFrame(self.tab_gd_nodedata)
        self.line_gd_do2.setGeometry(QtCore.QRect(10, 65, 451, 16))
        self.line_gd_do2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_gd_do2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_gd_do2.setObjectName("line_gd_do2")
        self.lbl_gd_click_to_next = QtWidgets.QLabel(self.tab_gd_nodedata)
        self.lbl_gd_click_to_next.setGeometry(QtCore.QRect(10, 40, 81, 21))
        self.lbl_gd_click_to_next.setObjectName("lbl_gd_click_to_next")
        self.cbox_gd_click_to_nex = QtWidgets.QComboBox(self.tab_gd_nodedata)
        self.cbox_gd_click_to_nex.setGeometry(QtCore.QRect(100, 40, 91, 22))
        self.cbox_gd_click_to_nex.setObjectName("cbox_gd_click_to_nex")
        self.lbl_gd_auto_to_next = QtWidgets.QLabel(self.tab_gd_nodedata)
        self.lbl_gd_auto_to_next.setGeometry(QtCore.QRect(270, 40, 81, 21))
        self.lbl_gd_auto_to_next.setObjectName("lbl_gd_auto_to_next")
        self.cbox_gd_auto_to_nex = QtWidgets.QComboBox(self.tab_gd_nodedata)
        self.cbox_gd_auto_to_nex.setGeometry(QtCore.QRect(360, 40, 91, 22))
        self.cbox_gd_auto_to_nex.setObjectName("cbox_gd_auto_to_nex")
        self.tab_gdtype_select.addTab(self.tab_gd_nodedata, "")
        self.lbl_gd_name = QtWidgets.QLabel(self.tab_main)
        self.lbl_gd_name.setGeometry(QtCore.QRect(4, 12, 48, 16))
        self.lbl_gd_name.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.lbl_gd_name.setObjectName("lbl_gd_name")
        self.le_gd_name = QtWidgets.QLineEdit(self.tab_main)
        self.le_gd_name.setGeometry(QtCore.QRect(50, 10, 401, 20))
        self.le_gd_name.setObjectName("le_gd_name")
        self.tab_GDfile_select.addTab(self.tab_main, "")
        self.tab_help = QtWidgets.QWidget()
        self.tab_help.setObjectName("tab_help")
        self.tab_GDfile_select.addTab(self.tab_help, "")
        self.gbox_preview = QtWidgets.QGroupBox(self.centralwidget)
        self.gbox_preview.setGeometry(QtCore.QRect(470, 0, 371, 541))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gbox_preview.setFont(font)
        self.gbox_preview.setObjectName("gbox_preview")
        self.pte_preview = QtWidgets.QPlainTextEdit(self.gbox_preview)
        self.pte_preview.setGeometry(QtCore.QRect(10, 30, 351, 461))
        self.pte_preview.setObjectName("pte_preview")
        self.btn_create = QtWidgets.QPushButton(self.gbox_preview)
        self.btn_create.setGeometry(QtCore.QRect(10, 500, 101, 31))
        self.btn_create.setObjectName("btn_create")
        self.btn_save = QtWidgets.QPushButton(self.gbox_preview)
        self.btn_save.setGeometry(QtCore.QRect(140, 500, 101, 31))
        self.btn_save.setObjectName("btn_save")
        self.btn_clear = QtWidgets.QPushButton(self.gbox_preview)
        self.btn_clear.setGeometry(QtCore.QRect(260, 500, 101, 31))
        self.btn_clear.setObjectName("btn_clear")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 850, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tab_GDfile_select.setCurrentIndex(0)
        self.tab_gdtype_select.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "引导工具Ver4.0"))
        self.lbl_gd_tri.setText(_translate("MainWindow", "Triggers"))
        self.lbl_gd_tri_type.setText(_translate("MainWindow", "触发类型："))
        self.lbl_gd_tri_cont1.setText(_translate("MainWindow", "content1"))
        self.lbl_gd_tri_cont2.setText(_translate("MainWindow", "content2"))
        self.lbl_gd_tri_cont3.setText(_translate("MainWindow", "content3"))
        self.tree_gd_tri.headerItem().setText(0, _translate("MainWindow", "Triggers"))
        self.tree_gd_tri.headerItem().setText(1, _translate("MainWindow", "Value"))
        self.lbl_gd_tri_list.setText(_translate("MainWindow", "触发条件列表"))
        self.btn_gd_tri_insert.setText(_translate("MainWindow", "插入"))
        self.btn_gd_tri_del.setText(_translate("MainWindow", "删除"))
        self.btn_gd_tri_upmove.setText(_translate("MainWindow", "上移"))
        self.btn_gd_tri_downmove.setText(_translate("MainWindow", "下移"))
        self.btn_gd_tri_clear.setText(_translate("MainWindow", "清空"))
        self.tab_gdtype_select.setTabText(self.tab_gdtype_select.indexOf(self.tab_gd_triggers),
                                          _translate("MainWindow", "触发条件"))
        self.lbl_gd_pre.setText(_translate("MainWindow", "Preconditions"))
        self.tree_gd_pre.headerItem().setText(1, _translate("MainWindow", "Value"))
        self.btn_gd_pre_upmove.setText(_translate("MainWindow", "上移"))
        self.btn_gd_pre_downmove.setText(_translate("MainWindow", "下移"))
        self.lbl_gd_pre_cont1.setText(_translate("MainWindow", "content1"))
        self.btn_gd_pre_del.setText(_translate("MainWindow", "删除"))
        self.btn_gd_pre_clear.setText(_translate("MainWindow", "清空"))
        self.lbl_gd_pre_type.setText(_translate("MainWindow", "条件类型："))
        self.lbl_gd_pre_list.setText(_translate("MainWindow", "前置条件列表"))
        self.lbl_gd_pre_cont2.setText(_translate("MainWindow", "content2"))
        self.btn_gd_pre_insert.setText(_translate("MainWindow", "插入"))
        self.lbl_gd_pre_cont3.setText(_translate("MainWindow", "content3"))
        self.tab_gdtype_select.setTabText(self.tab_gdtype_select.indexOf(self.tab_gd_preconditions),
                                          _translate("MainWindow", "前置条件"))
        self.lbl_gd_do_cont2.setText(_translate("MainWindow", "content2"))
        self.btn_gd_do_insert_big.setText(_translate("MainWindow", "插入（大）"))
        self.lbl_gd_do_type.setText(_translate("MainWindow", "效果类型："))
        self.lbl_gd_do_list.setText(_translate("MainWindow", "执行效果列表"))
        self.lbl_gd_do_cont3.setText(_translate("MainWindow", "content3"))
        self.btn_gd_do_downmove.setText(_translate("MainWindow", "下移"))
        self.btn_gd_do_clear.setText(_translate("MainWindow", "清空"))
        self.btn_gd_do_del.setText(_translate("MainWindow", "删除"))
        self.lbl_gd_do_cont1.setText(_translate("MainWindow", "content1"))
        self.btn_gd_del_upmove.setText(_translate("MainWindow", "上移"))
        self.tree_gd_do.headerItem().setText(1, _translate("MainWindow", "Value"))
        self.lbl_gd_nd.setText(_translate("MainWindow", "NodeData"))
        self.btn_gd_do_insert_small.setText(_translate("MainWindow", "插入（小）"))
        self.lbl_gd_do_cont4.setText(_translate("MainWindow", "content4"))
        self.lbl_gd_do_cont5.setText(_translate("MainWindow", "content5"))
        self.lbl_gd_click_to_next.setText(_translate("MainWindow", "IsClickToNext"))
        self.lbl_gd_auto_to_next.setText(_translate("MainWindow", "IsAutoToNext"))
        self.tab_gdtype_select.setTabText(self.tab_gdtype_select.indexOf(self.tab_gd_nodedata),
                                          _translate("MainWindow", "执行效果"))
        self.lbl_gd_name.setText(_translate("MainWindow", "引导名："))
        self.tab_GDfile_select.setTabText(self.tab_GDfile_select.indexOf(self.tab_main),
                                          _translate("MainWindow", "主引导"))
        self.tab_GDfile_select.setTabText(self.tab_GDfile_select.indexOf(self.tab_help),
                                          _translate("MainWindow", "帮助引导"))
        self.gbox_preview.setTitle(_translate("MainWindow", "引导预览："))
        self.btn_create.setText(_translate("MainWindow", "生成"))
        self.btn_save.setText(_translate("MainWindow", "保存"))
        self.btn_clear.setText(_translate("MainWindow", "清空"))
